In [11]:
import numpy as np

v = np.array([1,-1,2])
w = np.array([2,5,2])
print(v+w)
print(v-w)
print(3*v)
print(v*w)

print(np.linalg.norm(w))
print(np.dot(v,w))

[3 4 4]
[-1 -6  0]
[ 3 -3  6]
[ 2 -5  4]
5.744562646538029
1


In [31]:
# matrix 

a = np.array([[1,7],[3,5],[7,6]])
b = np.array([[1,3],[4,5],[6,8]])

c = np.add(a,b)
print(c)
# print(b)

[[ 2 10]
 [ 7 10]
 [13 14]]


In [37]:
d = np.subtract(a,b)
print
(d)

array([[ 0,  4],
       [-1,  0],
       [ 1, -2]])

In [41]:
e = np.subtract(b,a)
print(e)

[[ 0 -4]
 [ 1  0]
 [-1  2]]


In [45]:
f = np.add(b,a)
print(f)

[[ 2 10]
 [ 7 10]
 [13 14]]


In [55]:
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [57]:
R = np.array([[1,3,1],[1,0,1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [63]:
c2 = np.dot(P,R)
print(c2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [70]:
det = np.linalg.det(c2)
print(det)

0.0
